# Generated by Django 2.2 on 2020-02-14 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200215_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='step_no',
        ),
    ]
