# Generated by Django 2.2 on 2020-02-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_step_step_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-timestamp']},
        ),
    ]
